### ISSUE TITLE
Font size

### ISSUE THREAD

**Issue by BenoitTuybens** [driesbenoit/ugent-doc#3]
Hi Dries,

Very nice work. It looks fantastic! A small question however: is it possible to change the font size of your report/article/thesis? As the 12pt now seems unused (and changing it won't affect the font size). Sorry if this is a trivial question...

Cheers,
Benoît

**Comment by driesbenoit** [comment]
Hi Benoît,

Thanks for your interest in the package. I've just double checked and changing the global font size works for me. All document options that are not specific to `ugent-doc` will be passed to the underlying `article` or `report` class. Note that these document classes only support 10pt, 11pt and 12pt (see [LaTeX wiki](https://en.wikibooks.org/wiki/LaTeX/Fonts)). Please make sure you are using the last version of `ugent-doc`.

If this does not solve your issue, please provide a Minimal Working Example (MWE) that shows the problem.

Best,
Dries

**Comment by BenoitTuybens** [comment]
Hi Dries,

I was unaware of the fact that these document classes only support these three font sizes. I was experimenting with font sizes smaller (and bigger) than these 10p-12p. The issue is hereby solved. Sorry for the trivial question!

Cheers,
Benoît
