### ISSUE TITLE
Minus sign turns into an asterisk when compiling using LuaLatex

### ISSUE THREAD

**Issue by viktor40** [driesbenoit/ugent-doc#4]
When compiling with LuaLatex (which is recommended for some packages like tikz) using the  overleaf template. Some symbols aren't displayed correctly. Two of these I found is that the minus sign (-) turns into an asterisk (*). While the asterisk (*) turns into a less than (<) sign. The plus sign seems to be unaffected.

**Comment by driesbenoit** [comment]
Please provide a minimal example that reproduces the issue(s). Thanks.

**Comment by viktor40** [comment]
A minimal example that can be pasted into `main.tex` of the overleaf template provided in the `README.md` that produces this issue can be found below. This issue is only present for the LuaLaTeX compiler and the XeLaTeX compiler and isn't present for the PDFLaTeX compiler
```latex
\documentclass[12pt,a4paper,faculty=eb,language=en,doctype=article]{ugent-doc}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{libertine}
\usepackage{libertinust1math}
\usepackage[english]{babel} 
\usepackage{amsmath}
\usepackage{graphicx}
\graphicspath{{./figures/}}
\usepackage[backend=biber, style=apa, sorting=nyt, hyperref=true]{biblatex}
\addbibresource{./references.bib}
\usepackage{csquotes}
\usepackage[colorlinks=true, allcolors=ugentblue]{hyperref}

\usepackage[parfill]{parskip} 


\usepackage{ulem}
\renewcommand{\ULthickness}{2pt}
\thetitle{\uline{\color{ugentblue}The minus sign issue\newline A MINIMAL EXAMPLE}}

\begin{document}
\maketitle
\renewcommand{\ULthickness}{1pt}
\section*{Short summary}
Minus sign: $-$ \\
Asterisk: $*$ \\

{\Large \bf Use the LuaLaTeX or XeLaTex compiler in overleaf.\\PDFLaTeX doesn't produce this issue}

\end{document}
```

**Comment by driesbenoit** [comment]
This issue seems to be unrelated to the `ugent-doc` class, as I can reproduce it using the regular `article` class as well. Your issue seems to be linked to the `libertinust1math` package in combination with LuaLaTex/XeLaTex.
